用户体验优化
Archeb/Candy-Rebirth pull request #8
Opened 2018-04-07 18:33 UTC by lichaoxilcx

对源码作了一些小的改动，修复了一些小问题，希望能够提升主题使用的舒适性

2018-04-08 09:27 UTC, Archeb requested changes
超过三层深度的评论无法缩进 这个是故意设计的，如果缩进太深会不好看

2018-04-08 09:29 UTC, Archeb commented
其他的fix挺好的

2018-04-09 05:05 UTC, lichaoxilcx commented
之前的问题搞定了，但使用中发现一个新的问题，在使用 showArticle(url) 进行独立页面切换时会从`<div id="page"></div>`跳转回`<div id="archive"></div>`，然后再跳转到`<div id="page"></div>`，不知道你这边是否准备解决这个问题，或者说有什么好的设计？

2018-04-09 09:12 UTC, merged

2018-04-09 09:13 UTC, Archeb commented
因为要跳转的对象是当前自身，所以会出现这样的问题
可以考虑直接对page进行操作，移除原来的container
不过太懒没写